version: '3'

services:
    app:
        build: .
        volumes:
          - .:/fastapi_answerai
        ports:
          - 8000:8000

        image: app:fastapi_answerai
        container_name: fastapi_answerai_container
        command: uvicorn main:app --reload --port=8000 --host=0.0.0.0